'use strict';

const PDFDocument = require('pdfkit');

const RISK_COLORS = {
  low: '#1a7f37',
  medium: '#b45309',
  high: '#c0362c',
};

/**
 * Generates a screening report PDF as an in-memory buffer (no disk writes)
 * from a screening document (with patient populated) so the controller can
 * stream it straight back in the HTTP response.
 *
 * @param {object} screening - Mongoose screening doc (toObject'd), with patientId populated
 * @returns {Promise<Buffer>}
 */
function generateScreeningReportPdf(screening) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks = [];

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const patient = screening.patientId || {};
      const riskColor = RISK_COLORS[screening.riskLevel] || '#333333';

      // Header
      doc
        .fontSize(20)
        .fillColor('#0b3d91')
        .text('JointSaathi', { continued: true })
        .fillColor('#333333')
        .fontSize(12)
        .text('  |  Osteoarthritis Risk Screening Report', { align: 'left' });

      doc.moveDown(0.5);
      doc
        .strokeColor('#dddddd')
        .lineWidth(1)
        .moveTo(50, doc.y)
        .lineTo(545, doc.y)
        .stroke();
      doc.moveDown(1);

      // Patient details
      doc.fontSize(14).fillColor('#000000').text('Patient Details', { underline: true });
      doc.moveDown(0.3);
      doc.fontSize(11).fillColor('#333333');
      doc.text(`Name: ${patient.name || 'N/A'}`);
      doc.text(`Age: ${patient.age ?? 'N/A'}    Gender: ${patient.gender || 'N/A'}`);
      doc.text(`Village: ${patient.village || 'N/A'}`);
      doc.moveDown(1);

      // Screening details
      doc.fontSize(14).fillColor('#000000').text('Screening Details', { underline: true });
      doc.moveDown(0.3);
      doc.fontSize(11).fillColor('#333333');
      doc.text(`Date: ${new Date(screening.screeningDate).toLocaleString('en-IN')}`);
      doc.text(`Pain Level: ${screening.painLevel} / 10`);
      doc.text(`Stiffness Duration: ${screening.stiffnessDuration || 'Not reported'}`);
      doc.text(`Swelling: ${screening.swelling ? 'Yes' : 'No'}`);
      doc.text(`Past Injury: ${screening.pastInjury || 'None reported'}`);
      doc.moveDown(1);

      // Risk result (highlighted)
      doc.fontSize(14).fillColor('#000000').text('AI Risk Assessment', { underline: true });
      doc.moveDown(0.3);
      doc
        .fontSize(16)
        .fillColor(riskColor)
        .text(`Risk Level: ${screening.riskLevel.toUpperCase()}`, { continued: false });
      doc
        .fontSize(11)
        .fillColor('#333333')
        .text(
          `Confidence: ${
            typeof screening.confidence === 'number'
              ? `${Math.round(screening.confidence * 100)}%`
              : 'N/A'
          }`
        );
      doc.text(`Prediction Source: ${screening.source === 'ml_model' ? 'ML Model' : 'Rule-based Fallback'}`);
      doc.moveDown(0.5);

      if (screening.contributingFactors?.length) {
        doc.fontSize(11).fillColor('#000000').text('Contributing Factors:', { underline: false });
        screening.contributingFactors.forEach((factor) => {
          doc.fillColor('#333333').text(`  •  ${factor}`);
        });
        doc.moveDown(0.5);
      }

      if (screening.aiReasoning) {
        doc.fontSize(11).fillColor('#000000').text('AI Reasoning:');
        doc.fillColor('#333333').text(screening.aiReasoning, { align: 'justify' });
        doc.moveDown(0.5);
      }

      if (screening.doctorRecommendations) {
        doc.fontSize(11).fillColor('#000000').text('Recommendations:');
        doc.fillColor('#333333').text(screening.doctorRecommendations, { align: 'justify' });
      }

      doc.moveDown(2);
      doc
        .fontSize(9)
        .fillColor('#999999')
        .text(
          'This report is generated by an AI-assisted screening tool and is not a substitute ' +
            'for professional medical diagnosis. Please consult a qualified physician.',
          { align: 'center' }
        );

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { generateScreeningReportPdf };
