import json

translations = {
    "bn": {
        "past_medical_history": "অতীতের চিকিৎসার ইতিহাস",
        "previous_diagnosis_of_arthritis": "আর্থ্রাইটিসের পূর্ববর্তী রোগ নির্ণয়",
        "previous_joint_pain_episodes": "আগের অস্থিসন্ধির ব্যথার ঘটনা",
        "chronic_joint_problems": "দীর্ঘস্থায়ী অস্থিসন্ধির সমস্যা",
        "previous_joint_inflammation_swelling": "অস্থিসন্ধিতে ফোলা/প্রদাহ",
        "history_of_injury_to_this_joint": "এই অস্থিসন্ধিতে আঘাতের ইতিহাস",
        "for_side_joint": "{side} {joint} এর জন্য",
        "past_surgeries": "অতীতের অস্ত্রোপচার",
        "have_you_had_surgery_on_this_joint": "আপনার কি এই অস্থিসন্ধিতে অস্ত্রোপচার হয়েছে?",
        "surgery_details": "অস্ত্রোপচারের বিবরণ",
        "type_of_surgery": "অস্ত্রোপচারের ধরন",
        "are_there_implants_hardware": "কোনো ইমপ্লান্ট/হার্ডওয়্যার উপস্থিত আছে কি?",
        "question_4_mri": "প্রশ্ন ৪: এমআরআই রিপোর্ট",
        "mri_scan_medical_report": "এমআরআই স্ক্যান / মেডিকেল রিপোর্ট",
        "mri_hint": "যদি রোগীর এমআরআই রিপোর্ট থাকে, তবে গ্রেড (KL Grade) নির্বাচন করুন।",
        "mri_normal_none": "স্বাভাবিক / নেই",
        "mri_normal_desc": "কোনো এমআরআই নেই বা সুস্থ অস্থিসন্ধি",
        "mri_grade1_doubtful": "গ্রেড ১: সন্দেহজনক",
        "mri_grade1_desc": "সন্দেহজনক সন্ধিস্থান সংকীর্ণ হওয়া",
        "mri_grade2_mild": "গ্রেড ২: মৃদু",
        "mri_grade2_desc": "নিশ্চিত অস্টিওফাইট, সম্ভাব্য সংকীর্ণতা",
        "mri_grade3_moderate": "গ্রেড ৩: মাঝারি",
        "mri_grade3_desc": "একাধিক অস্টিওফাইট, নিশ্চিত সংকীর্ণতা",
        "mri_grade4_severe": "গ্রেড ৪: গুরুতর",
        "mri_grade4_desc": "বড় অস্টিওফাইট, গুরুতর সংকীর্ণতা",
        "question_5_symptoms": "প্রশ্ন ৫: লক্ষণসমূহ",
        "expanded_symptoms": "বিস্তারিত লক্ষণসমূহ",
        "expanded_symptoms_hint": "আপনি অন্য কোনো লক্ষণ অনুভব করলে নির্বাচন করুন।",
        "pain_characteristics": "ব্যথার ধরন",
        "pain_sharp": "তীব্র ব্যথা",
        "pain_dull": "মৃদু ব্যথা",
        "pain_burning": "জ্বলন",
        "pain_aching": "টানা ব্যথা",
        "pain_stabbing": "বিদ্ধ করার মতো ব্যথা",
        "pain_throbbing": "দপ দপ করা ব্যথা",
        "stiffness_triggers": "আড়ষ্টতার কারণ",
        "stiff_morning": "সকালে",
        "stiff_after_sitting": "বসার পর",
        "stiff_after_inactivity": "নিষ্ক্রিয়তার পর",
        "stiff_after_exercise": "ব্যায়ামের পর",
        "other_observations": "অন্যান্য লক্ষণ",
        "sym_warmth": "গরম অনুভব",
        "sym_redness": "লাল হওয়া",
        "sym_tenderness": "স্পর্শ করলে ব্যথা (টেন্ডারনেস)",
        "sym_clicking": "ক্লিক শব্দ",
        "sym_grinding": "ঘষার শব্দ",
        "sym_locking": "সন্ধি আটকে যাওয়া",
        "sym_giving_way": "সন্ধি সরে যাওয়া",
        "sym_instability": "অস্থिरতা",
        "sym_reduced_mobility": "গতিশীলতা কমে যাওয়া"
    },
    "gu": {
        "past_medical_history": "ભૂતકાળનો તબીબી ઇતિહાસ",
        "previous_diagnosis_of_arthritis": "સંધિવાનું અગાઉનું નિદાન",
        "previous_joint_pain_episodes": "અગાઉના સાંધાના દુખાવાના એપિસોડ",
        "chronic_joint_problems": "લાંબા સમયથી સાંધાની સમસ્યાઓ",
        "previous_joint_inflammation_swelling": "સાંધામાં સોજો/બળતરા",
        "history_of_injury_to_this_joint": "આ સાંધામાં ઈજાનો ઇતિહાસ",
        "for_side_joint": "{side} {joint} માટે",
        "past_surgeries": "ભૂતકાળની સર્જરીઓ",
        "have_you_had_surgery_on_this_joint": "શું તમારી આ સાંધા પર સર્જરી થઈ છે?",
        "surgery_details": "સર્જરીની વિગતો",
        "type_of_surgery": "સર્જરીનો પ્રકાર",
        "are_there_implants_hardware": "શું કોઈ ઇમ્પ્લાન્ટ/હાર્ડવેર હાજર છે?",
        "question_4_mri": "પ્રશ્ન ૪: MRI રિપોર્ટ",
        "mri_scan_medical_report": "MRI સ્કેન / મેડિકલ રિપોર્ટ",
        "mri_hint": "જો દર્દીનો MRI રિપોર્ટ હોય, તો ગ્રેડ (KL Grade) પસંદ કરો.",
        "mri_normal_none": "સામાન્ય / કંઈ નહિ",
        "mri_normal_desc": "કોઈ MRI નથી અથવા સ્વસ્થ સાંધા",
        "mri_grade1_doubtful": "ગ્રેડ ૧: શંકાસ્પદ",
        "mri_grade1_desc": "સાંધાની જગ્યામાં શંકાસ્પદ સંકોચન",
        "mri_grade2_mild": "ગ્રેડ ૨: હળવો",
        "mri_grade2_desc": "નિશ્ચિત ઓસ્ટિઓફાઇટ્સ, સંભવિત સંકોચન",
        "mri_grade3_moderate": "ગ્રેડ ૩: મધ્યમ",
        "mri_grade3_desc": "બહુવિધ ઓસ્ટિઓફાઇટ્સ, નિશ્ચિત સંકોચન",
        "mri_grade4_severe": "ગ્રેડ ૪: ગંભીર",
        "mri_grade4_desc": "મોટા ઓસ્ટિઓફાઇટ્સ, ગંભીર સંકોચન",
        "question_5_symptoms": "પ્રશ્ન ૫: લક્ષણો",
        "expanded_symptoms": "વિસ્તૃત લક્ષણો",
        "expanded_symptoms_hint": "જો તમે અન્ય કોઈ લક્ષણો અનુભવી રહ્યા હોવ તો તે પસંદ કરો.",
        "pain_characteristics": "દુખાવાના લક્ષણો",
        "pain_sharp": "તીવ્ર દુખાવો",
        "pain_dull": "હળવો દુખાવો",
        "pain_burning": "બળતરા",
        "pain_aching": "સતત દુખાવો",
        "pain_stabbing": "છરા મારવા જેવો દુખાવો",
        "pain_throbbing": "ધબકતો દુખાવો",
        "stiffness_triggers": "અકળામણના કારણો",
        "stiff_morning": "સવારે",
        "stiff_after_sitting": "બેઠા પછી",
        "stiff_after_inactivity": "નિષ્ક્રિયતા પછી",
        "stiff_after_exercise": "કસરત પછી",
        "other_observations": "અન્ય લક્ષણો",
        "sym_warmth": "ગરમ લાગવું",
        "sym_redness": "લાલાશ",
        "sym_tenderness": "અડકવાથી દુખાવો (ટેન્ડરનેસ)",
        "sym_clicking": "ક્લિકિંગ અવાજ",
        "sym_grinding": "ઘસાવાનો અવાજ",
        "sym_locking": "સાંધો લોક થવો",
        "sym_giving_way": "સાંધો ખસી જવો",
        "sym_instability": "અસ્થિરતા",
        "sym_reduced_mobility": "હલનચલનમાં ઘટાડો"
    },
    "mr": {
        "past_medical_history": "मागील वैद्यकीय इतिहास",
        "previous_diagnosis_of_arthritis": "संधिवाताचे पूर्वीचे निदान",
        "previous_joint_pain_episodes": "मागील सांधेदुखीचे प्रकार",
        "chronic_joint_problems": "तीव्र सांध्याचे आजार",
        "previous_joint_inflammation_swelling": "सांध्यामध्ये सूज/दाह",
        "history_of_injury_to_this_joint": "या सांध्याला दुखापतीचा इतिहास",
        "for_side_joint": "{side} {joint} साठी",
        "past_surgeries": "मागील शस्त्रक्रिया",
        "have_you_had_surgery_on_this_joint": "या सांध्यावर तुमची शस्त्रक्रिया झाली आहे का?",
        "surgery_details": "शस्त्रक्रियेचा तपशील",
        "type_of_surgery": "शस्त्रक्रियेचा प्रकार",
        "are_there_implants_hardware": "कोणतेही रोपण/हार्डवेअर अस्तित्वात आहे का?",
        "question_4_mri": "प्रश्न ४: MRI अहवाल",
        "mri_scan_medical_report": "MRI स्कॅन / वैद्यकीय अहवाल",
        "mri_hint": "रुग्णाचा MRI अहवाल असल्यास, ग्रेड (KL Grade) निवडा.",
        "mri_normal_none": "सामान्य / काहीही नाही",
        "mri_normal_desc": "कोणताही MRI नाही किंवा निरोगी सांधे",
        "mri_grade1_doubtful": "ग्रेड १: संशयास्पद",
        "mri_grade1_desc": "संशयास्पद सांध्याची जागा अरुंद होणे",
        "mri_grade2_mild": "ग्रेड २: सौम्य",
        "mri_grade2_desc": "निश्चित ऑस्टियोफाइट्स, संभाव्य अरुंदता",
        "mri_grade3_moderate": "ग्रेड ३: मध्यम",
        "mri_grade3_desc": "एकाधिक ऑस्टियोफाइट्स, निश्चित अरुंदता",
        "mri_grade4_severe": "ग्रेड ४: गंभीर",
        "mri_grade4_desc": "मोठे ऑस्टियोफाइट्स, गंभीर अरुंदता",
        "question_5_symptoms": "प्रश्न ५: लक्षणे",
        "expanded_symptoms": "विस्तृत लक्षणे",
        "expanded_symptoms_hint": "तुम्हाला इतर कोणतीही लक्षणे जाणवत असल्यास ती निवडा.",
        "pain_characteristics": "वेदनांची वैशिष्ट्ये",
        "pain_sharp": "तीव्र वेदना",
        "pain_dull": "सौम्य वेदना",
        "pain_burning": "जळजळ",
        "pain_aching": "सतत वेदना",
        "pain_stabbing": "खुपसल्यासारखी वेदना",
        "pain_throbbing": "ठणकणारी वेदना",
        "stiffness_triggers": "कडकपणा वाढवणारी कारणे",
        "stiff_morning": "सकाळी",
        "stiff_after_sitting": "बसल्यानंतर",
        "stiff_after_inactivity": "निष्क्रियतेनंतर",
        "stiff_after_exercise": "व्यायामानंतर",
        "other_observations": "इतर लक्षणे",
        "sym_warmth": "उबदारपणा",
        "sym_redness": "लालसरपणा",
        "sym_tenderness": "स्पर्श केल्यास वेदना (टेंडरनेस)",
        "sym_clicking": "क्लिक करणारा आवाज",
        "sym_grinding": "घासण्याचा आवाज",
        "sym_locking": "सांधा लॉक होणे",
        "sym_giving_way": "सांधा निखळणे",
        "sym_instability": "अस्थिरता",
        "sym_reduced_mobility": "गतिशीलता कमी होणे"
    },
    "pa": {
        "past_medical_history": "ਪਿਛਲਾ ਡਾਕਟਰੀ ਇਤਿਹਾਸ",
        "previous_diagnosis_of_arthritis": "ਗਠੀਏ ਦਾ ਪਿਛਲਾ ਨਿਦਾਨ",
        "previous_joint_pain_episodes": "ਜੋੜਾਂ ਦੇ ਦਰਦ ਦੀਆਂ ਪਿਛਲੀਆਂ ਘਟਨਾਵਾਂ",
        "chronic_joint_problems": "ਲੰਬੇ ਸਮੇਂ ਤੋਂ ਜੋੜਾਂ ਦੀਆਂ ਸਮੱਸਿਆਵਾਂ",
        "previous_joint_inflammation_swelling": "ਜੋੜਾਂ ਵਿੱਚ ਸੋਜ",
        "history_of_injury_to_this_joint": "ਇਸ ਜੋੜ ਦੀ ਸੱਟ ਦਾ ਇਤਿਹਾਸ",
        "for_side_joint": "{side} {joint} ਲਈ",
        "past_surgeries": "ਪਿਛਲੀਆਂ ਸਰਜਰੀਆਂ",
        "have_you_had_surgery_on_this_joint": "ਕੀ ਤੁਹਾਡੀ ਇਸ ਜੋੜ ਦੀ ਸਰਜਰੀ ਹੋਈ ਹੈ?",
        "surgery_details": "ਸਰਜਰੀ ਦੇ ਵੇਰਵੇ",
        "type_of_surgery": "ਸਰਜਰੀ ਦੀ ਕਿਸਮ",
        "are_there_implants_hardware": "ਕੀ ਕੋਈ ਇਮਪਲਾਂਟ/ਹਾਰਡਵੇਅਰ ਮੌਜੂਦ ਹੈ?",
        "question_4_mri": "ਪ੍ਰਸ਼ਨ 4: ਐਮ.ਆਰ.ਆਈ. ਰਿਪੋਰਟ",
        "mri_scan_medical_report": "ਐਮ.ਆਰ.ਆਈ. ਸਕੈਨ / ਮੈਡੀਕਲ ਰਿਪੋਰਟ",
        "mri_hint": "ਜੇ ਮਰੀਜ਼ ਦੀ ਐਮ.ਆਰ.ਆਈ. ਰਿਪੋਰਟ ਹੈ, ਤਾਂ ਗ੍ਰੇਡ (KL Grade) ਚੁਣੋ।",
        "mri_normal_none": "ਆਮ / ਕੋਈ ਨਹੀਂ",
        "mri_normal_desc": "ਕੋਈ ਐਮ.ਆਰ.ਆਈ. ਨਹੀਂ ਜਾਂ ਸਿਹਤਮੰਦ ਜੋੜ",
        "mri_grade1_doubtful": "ਗ੍ਰੇਡ 1: ਸ਼ੱਕੀ",
        "mri_grade1_desc": "ਸ਼ੱਕੀ ਜੋੜ ਸਥਾਨ ਦਾ ਸੁੰਗੜਨਾ",
        "mri_grade2_mild": "ਗ੍ਰੇਡ 2: ਹਲਕਾ",
        "mri_grade2_desc": "ਨਿਸ਼ਚਿਤ ਓਸਟੀਓਫਾਈਟਸ, ਸੰਭਾਵਿਤ ਸੁੰਗੜਨਾ",
        "mri_grade3_moderate": "ਗ੍ਰੇਡ 3: ਦਰਮਿਆਨਾ",
        "mri_grade3_desc": "ਕਈ ਓਸਟੀਓਫਾਈਟਸ, ਨਿਸ਼ਚਿਤ ਸੁੰਗੜਨਾ",
        "mri_grade4_severe": "ਗ੍ਰੇਡ 4: ਗੰਭੀਰ",
        "mri_grade4_desc": "ਵੱਡੇ ਓਸਟੀਓਫਾਈਟਸ, ਗੰਭੀਰ ਸੁੰਗੜਨਾ",
        "question_5_symptoms": "ਪ੍ਰਸ਼ਨ 5: ਲੱਛਣ",
        "expanded_symptoms": "ਵਿਸਤ੍ਰਿਤ ਲੱਛਣ",
        "expanded_symptoms_hint": "ਜੇ ਤੁਸੀਂ ਕੋਈ ਹੋਰ ਲੱਛਣ ਮਹਿਸੂਸ ਕਰ ਰਹੇ ਹੋ ਤਾਂ ਚੁਣੋ।",
        "pain_characteristics": "ਦਰਦ ਦੀਆਂ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
        "pain_sharp": "ਤੇਜ਼ ਦਰਦ",
        "pain_dull": "ਹਲਕਾ ਦਰਦ",
        "pain_burning": "ਜਲਣ",
        "pain_aching": "ਲਗਾਤਾਰ ਦਰਦ",
        "pain_stabbing": "ਚੁੱਭਣ ਵਾਲਾ ਦਰਦ",
        "pain_throbbing": "ਧੜਕਣ ਵਾਲਾ ਦਰਦ",
        "stiffness_triggers": "ਅਕੜਾਅ ਦੇ ਕਾਰਨ",
        "stiff_morning": "ਸਵੇਰੇ",
        "stiff_after_sitting": "ਬੈਠਣ ਤੋਂ ਬਾਅਦ",
        "stiff_after_inactivity": "ਅਕਿਰਿਆਸ਼ੀਲਤਾ ਤੋਂ ਬਾਅਦ",
        "stiff_after_exercise": "ਕਸਰਤ ਤੋਂ ਬਾਅਦ",
        "other_observations": "ਹੋਰ ਲੱਛਣ",
        "sym_warmth": "ਗਰਮ ਲੱਗਣਾ",
        "sym_redness": "ਲਾਲ ਹੋਣਾ",
        "sym_tenderness": "ਛੂਹਣ 'ਤੇ ਦਰਦ",
        "sym_clicking": "ਕਲਿੱਕ ਕਰਨ ਦੀ ਆਵਾਜ਼",
        "sym_grinding": "ਰਗੜਨ ਦੀ ਆਵਾਜ਼",
        "sym_locking": "ਜੋੜ ਲਾਕ ਹੋਣਾ",
        "sym_giving_way": "ਜੋੜ ਖਿਸਕਣਾ",
        "sym_instability": "ਅਸਥਿਰਤਾ",
        "sym_reduced_mobility": "ਗਤੀਸ਼ੀਲਤਾ ਵਿੱਚ ਕਮੀ"
    },
    "ta": {
        "past_medical_history": "முந்தைய மருத்துவ வரலாறு",
        "previous_diagnosis_of_arthritis": "முந்தைய மூட்டுவலி நோயறிதல்",
        "previous_joint_pain_episodes": "முந்தைய மூட்டு வலி நிகழ்வுகள்",
        "chronic_joint_problems": "நாள்பட்ட மூட்டு பிரச்சனைகள்",
        "previous_joint_inflammation_swelling": "மூட்டு வீக்கம்",
        "history_of_injury_to_this_joint": "இந்த மூட்டில் ஏற்பட்ட காயத்தின் வரலாறு",
        "for_side_joint": "{side} {joint} க்கு",
        "past_surgeries": "முந்தைய அறுவை சிகிச்சைகள்",
        "have_you_had_surgery_on_this_joint": "இந்த மூட்டில் உங்களுக்கு அறுவை சிகிச்சை செய்யப்பட்டுள்ளதா?",
        "surgery_details": "அறுவை சிகிச்சை விவரங்கள்",
        "type_of_surgery": "அறுவை சிகிச்சையின் வகை",
        "are_there_implants_hardware": "ஏதேனும் உள்வைப்புகள்/வன்பொருள் உள்ளதா?",
        "question_4_mri": "கேள்வி 4: எம்.ஆர்.ஐ அறிக்கை",
        "mri_scan_medical_report": "எம்.ஆர்.ஐ ஸ்கேன் / மருத்துவ அறிக்கை",
        "mri_hint": "நோயாளியின் எம்.ஆர்.ஐ அறிக்கை இருந்தால், தரம் (KL Grade) தேர்வு செய்யவும்.",
        "mri_normal_none": "இயல்பான / ஏதுமில்லை",
        "mri_normal_desc": "எம்.ஆர்.ஐ இல்லை அல்லது ஆரோக்கியமான மூட்டுகள்",
        "mri_grade1_doubtful": "தரம் 1: சந்தேகத்திற்கிடமானது",
        "mri_grade1_desc": "சந்தேகத்திற்கிடமான மூட்டு இடைவெளி குறுகுதல்",
        "mri_grade2_mild": "தரம் 2: லேசானது",
        "mri_grade2_desc": "உறுதியான ஆஸ்டியோபைட்டுகள், சாத்தியமான குறுகுதல்",
        "mri_grade3_moderate": "தரம் 3: மிதமானது",
        "mri_grade3_desc": "பல ஆஸ்டியோபைட்டுகள், உறுதியான குறுகுதல்",
        "mri_grade4_severe": "தரம் 4: கடுமையானது",
        "mri_grade4_desc": "பெரிய ஆஸ்டியோபைட்டுகள், கடுமையான குறுகுதல்",
        "question_5_symptoms": "கேள்வி 5: அறிகுறிகள்",
        "expanded_symptoms": "விரிவான அறிகுறிகள்",
        "expanded_symptoms_hint": "நீங்கள் வேறு ஏதேனும் அறிகுறிகளை அனுபவித்தால் அவற்றைத் தேர்ந்தெடுக்கவும்.",
        "pain_characteristics": "வலியின் பண்புகள்",
        "pain_sharp": "கடுமையான வலி",
        "pain_dull": "மந்தமான வலி",
        "pain_burning": "எரியும் உணர்வு",
        "pain_aching": "தொடர்ச்சியான வலி",
        "pain_stabbing": "குத்துவது போன்ற வலி",
        "pain_throbbing": "துடிக்கும் வலி",
        "stiffness_triggers": "விறைப்புக்கான காரணங்கள்",
        "stiff_morning": "காலையில்",
        "stiff_after_sitting": "உட்கார்ந்த பிறகு",
        "stiff_after_inactivity": "செயலற்ற தன்மைக்குப் பிறகு",
        "stiff_after_exercise": "உடற்பயிற்சிக்குப் பிறகு",
        "other_observations": "பிற அறிகுறிகள்",
        "sym_warmth": "வெப்ப உணர்வு",
        "sym_redness": "சிவத்தல்",
        "sym_tenderness": "தொட்டால் வலி",
        "sym_clicking": "க்ளிக் செய்யும் சத்தம்",
        "sym_grinding": "உராய்வு சத்தம்",
        "sym_locking": "மூட்டு பூட்டிக்கொள்ளுதல்",
        "sym_giving_way": "மூட்டு தளர்வது போன்ற உணர்வு",
        "sym_instability": "நிலையற்ற தன்மை",
        "sym_reduced_mobility": "இயக்கம் குறைதல்"
    },
    "te": {
        "past_medical_history": "గత వైద్య చరిత్ర",
        "previous_diagnosis_of_arthritis": "గతంలో ఆర్థరైటిస్ నిర్ధారణ",
        "previous_joint_pain_episodes": "గత కీళ్ల నొప్పుల సంఘటనలు",
        "chronic_joint_problems": "దీర్ఘకాలిక కీళ్ల సమస్యలు",
        "previous_joint_inflammation_swelling": "కీళ్ల వాపు",
        "history_of_injury_to_this_joint": "ఈ కీలుకు గాయం అయిన చరిత్ర",
        "for_side_joint": "{side} {joint} కోసం",
        "past_surgeries": "గత శస్త్రచికిత్సలు",
        "have_you_had_surgery_on_this_joint": "మీకు ఈ కీలుపై శస్త్రచికిత్స జరిగిందా?",
        "surgery_details": "శస్త్రచికిత్స వివరాలు",
        "type_of_surgery": "శస్త్రచికిత్స రకం",
        "are_there_implants_hardware": "ఏవైనా ఇంప్లాంట్లు/హార్డ్‌వేర్ ఉన్నాయా?",
        "question_4_mri": "ప్రశ్న 4: ఎం.ఆర్.ఐ నివేదిక",
        "mri_scan_medical_report": "ఎం.ఆర్.ఐ స్కాన్ / వైద్య నివేదిక",
        "mri_hint": "రోగి ఎం.ఆర్.ఐ నివేదిక ఉన్నట్లయితే, గ్రేడ్ (KL Grade) ఎంచుకోండి.",
        "mri_normal_none": "సాధారణ / ఏమీ లేదు",
        "mri_normal_desc": "ఎం.ఆర్.ఐ లేదు లేదా ఆరోగ్యకరమైన కీళ్ళు",
        "mri_grade1_doubtful": "గ్రేడ్ 1: అనుమానాస్పదంగా ఉంది",
        "mri_grade1_desc": "అనుమానాస్పద కీలు స్థలం సంకోచం",
        "mri_grade2_mild": "గ్రేడ్ 2: తేలికపాటి",
        "mri_grade2_desc": "కచ్చితమైన ఆస్టియోఫైట్స్, సంకోచం జరిగే అవకాశం ఉంది",
        "mri_grade3_moderate": "గ్రేడ్ 3: మోస్తరు",
        "mri_grade3_desc": "బహుళ ఆస్టియోఫైట్స్, కచ్చితమైన సంకోచం",
        "mri_grade4_severe": "గ్రేడ్ 4: తీవ్రమైన",
        "mri_grade4_desc": "పెద్ద ఆస్టియోఫైట్స్, తీవ్రమైన సంకోచం",
        "question_5_symptoms": "ప్రశ్న 5: లక్షణాలు",
        "expanded_symptoms": "వివరణాత్మక లక్షణాలు",
        "expanded_symptoms_hint": "మీరు మరేవైనా ఇతర లక్షణాలను అనుభవిస్తుంటే వాటిని ఎంచుకోండి.",
        "pain_characteristics": "నొప్పి లక్షణాలు",
        "pain_sharp": "తీవ్రమైన నొప్పి",
        "pain_dull": "మందకొడి నొప్పి",
        "pain_burning": "మంట",
        "pain_aching": "కొనసాగుతున్న నొప్పి",
        "pain_stabbing": "పొడుస్తున్నట్లుగా నొప్పి",
        "pain_throbbing": "కొట్టుకుంటున్నట్లు నొప్పి",
        "stiffness_triggers": "బిగువుకు కారణాలు",
        "stiff_morning": "ఉదయం",
        "stiff_after_sitting": "కూర్చున్న తర్వాత",
        "stiff_after_inactivity": "క్రియారహితంగా ఉన్న తర్వాత",
        "stiff_after_exercise": "వ్యాయామం తర్వాత",
        "other_observations": "ఇతర లక్షణాలు",
        "sym_warmth": "వెచ్చదనం",
        "sym_redness": "ఎరుపుగా ఉండటం",
        "sym_tenderness": "తాకితే నొప్పి (టెండర్‌నెస్)",
        "sym_clicking": "క్లిక్ అనే శబ్దం",
        "sym_grinding": "రుద్దినట్లు శబ్దం రావడం",
        "sym_locking": "కీలు లాక్ అవ్వడం",
        "sym_giving_way": "కీలు పట్టు కోల్పోవడం",
        "sym_instability": "అస్థిరత",
        "sym_reduced_mobility": "కదలిక తగ్గడం"
    },
    "kn": {
        "past_medical_history": "ಹಿಂದಿನ ವೈದ್ಯಕೀಯ ಇತಿಹಾಸ",
        "previous_diagnosis_of_arthritis": "ಸಂಧಿವಾತದ ಹಿಂದಿನ ರೋಗನಿರ್ಣಯ",
        "previous_joint_pain_episodes": "ಹಿಂದಿನ ಕೀಲು ನೋವಿನ ಘಟನೆಗಳು",
        "chronic_joint_problems": "ದೀರ್ಘಕಾಲದ ಕೀಲು ಸಮಸ್ಯೆಗಳು",
        "previous_joint_inflammation_swelling": "ಕೀಲು ಊತ",
        "history_of_injury_to_this_joint": "ಈ ಕೀಲಿನ ಗಾಯದ ಇತಿಹಾಸ",
        "for_side_joint": "{side} {joint} ಗಾಗಿ",
        "past_surgeries": "ಹಿಂದಿನ ಶಸ್ತ್ರಚಿಕಿತ್ಸೆಗಳು",
        "have_you_had_surgery_on_this_joint": "ಈ ಕೀಲಿನ ಮೇಲೆ ಶಸ್ತ್ರಚಿಕಿತ್ಸೆ ಆಗಿದೆಯೇ?",
        "surgery_details": "ಶಸ್ತ್ರಚಿಕಿತ್ಸೆ ವಿವರಗಳು",
        "type_of_surgery": "ಶಸ್ತ್ರಚಿಕಿತ್ಸೆಯ ಪ್ರಕಾರ",
        "are_there_implants_hardware": "ಯಾವುದಾದರೂ ಇಂಪ್ಲಾಂಟ್/ಹಾರ್ಡ್‌ವೇರ್ ಇದೆಯೇ?",
        "question_4_mri": "ಪ್ರಶ್ನೆ ೪: ಎಂ.ಆರ್.ಐ ವರದಿ",
        "mri_scan_medical_report": "ಎಂ.ಆರ್.ಐ ಸ್ಕ್ಯಾನ್ / ವೈದ್ಯಕೀಯ ವರದಿ",
        "mri_hint": "ರೋಗಿಯ ಎಂ.ಆರ್.ಐ ವರದಿ ಇದ್ದರೆ, ಗ್ರೇಡ್ (KL Grade) ಆಯ್ಕೆಮಾಡಿ.",
        "mri_normal_none": "ಸಾಮಾನ್ಯ / ಇಲ್ಲ",
        "mri_normal_desc": "ಎಂ.ಆರ್.ಐ ಇಲ್ಲ ಅಥವಾ ಆರೋಗ್ಯಕರ ಕೀಲುಗಳು",
        "mri_grade1_doubtful": "ಗ್ರೇಡ್ ೧: ಅನುಮಾನಾಸ್ಪದ",
        "mri_grade1_desc": "ಅನುಮಾನಾಸ್ಪದ ಕೀಲು ಜಾಗದ ಸಂಕುಚಿತತೆ",
        "mri_grade2_mild": "ಗ್ರೇಡ್ ೨: ಸೌಮ್ಯ",
        "mri_grade2_desc": "ನಿಶ್ಚಿತ ಆಸ್ಟಿಯೋಫೈಟ್ಸ್, ಸಂಭವನೀಯ ಸಂಕುಚಿತತೆ",
        "mri_grade3_moderate": "ಗ್ರೇಡ್ ೩: ಸಾಧಾರಣ",
        "mri_grade3_desc": "ಬಹು ಆಸ್ಟಿಯೋಫೈಟ್ಸ್, ನಿಶ್ಚಿತ ಸಂಕುಚಿತತೆ",
        "mri_grade4_severe": "ಗ್ರೇಡ್ ೪: ತೀವ್ರ",
        "mri_grade4_desc": "ದೊಡ್ಡ ಆಸ್ಟಿಯೋಫೈಟ್ಸ್, ತೀವ್ರ ಸಂಕುಚಿತತೆ",
        "question_5_symptoms": "ಪ್ರಶ್ನೆ ೫: ಲಕ್ಷಣಗಳು",
        "expanded_symptoms": "ವಿವರವಾದ ಲಕ್ಷಣಗಳು",
        "expanded_symptoms_hint": "ನೀವು ಇತರ ಯಾವುದೇ ಲಕ್ಷಣಗಳನ್ನು ಹೊಂದಿದ್ದರೆ ಆಯ್ಕೆಮಾಡಿ.",
        "pain_characteristics": "ನೋವಿನ ಗುಣಲಕ್ಷಣಗಳು",
        "pain_sharp": "ತೀವ್ರ ನೋವು",
        "pain_dull": "ಮಂದ ನೋವು",
        "pain_burning": "ಉರಿ",
        "pain_aching": "ನಿರಂತರ ನೋವು",
        "pain_stabbing": "ಚುಚ್ಚುವಂತಹ ನೋವು",
        "pain_throbbing": "ಬಡಿಯುವಂತಹ ನೋವು",
        "stiffness_triggers": "ಬಿಗಿತಕ್ಕೆ ಕಾರಣಗಳು",
        "stiff_morning": "ಬೆಳಗ್ಗೆ",
        "stiff_after_sitting": "ಕುಳಿತ ನಂತರ",
        "stiff_after_inactivity": "ನಿಷ್ಕ್ರಿಯತೆಯ ನಂತರ",
        "stiff_after_exercise": "ವ್ಯಾಯಾಮದ ನಂತರ",
        "other_observations": "ಇತರ ಲಕ್ಷಣಗಳು",
        "sym_warmth": "ಬೆಚ್ಚನೆಯ ಭಾವನೆ",
        "sym_redness": "ಕೆಂಪು ಬಣ್ಣ",
        "sym_tenderness": "ಮುಟ್ಟಿದರೆ ನೋವು",
        "sym_clicking": "ಕ್ಲಿಕ್ ಮಾಡುವ ಶಬ್ದ",
        "sym_grinding": "ಉಜ್ಜಿದಂತಹ ಶಬ್ದ",
        "sym_locking": "ಕೀಲು ಲಾಕ್ ಆಗುವುದು",
        "sym_giving_way": "ಕೀಲು ಜಾರುವುದು",
        "sym_instability": "ಅಸ್ಥಿರತೆ",
        "sym_reduced_mobility": "ಚಲನೆ ಕಡಿಮೆಯಾಗುವುದು"
    },
    "ml": {
        "past_medical_history": "മുൻകാല മെഡിക്കൽ ചരിത്രം",
        "previous_diagnosis_of_arthritis": "ആർത്രൈറ്റിസിന്റെ മുൻ പരിശോധന",
        "previous_joint_pain_episodes": "മുൻകാല സന്ധി വേദനകൾ",
        "chronic_joint_problems": "വിട്ടുമാറാത്ത സന്ധി പ്രശ്നങ്ങൾ",
        "previous_joint_inflammation_swelling": "സന്ധി വീക്കം",
        "history_of_injury_to_this_joint": "സന്ധിയിലെ പരിക്കിന്റെ ചരിത്രം",
        "for_side_joint": "{side} {joint} നായി",
        "past_surgeries": "മുൻകാല ശസ്ത്രക്രിയകൾ",
        "have_you_had_surgery_on_this_joint": "ഈ സന്ധിയിൽ ശസ്ത്രക്രിയ നടത്തിയിട്ടുണ്ടോ?",
        "surgery_details": "ശസ്ത്രക്രിയ വിവരങ്ങൾ",
        "type_of_surgery": "ശസ്ത്രക്രിയയുടെ തരം",
        "are_there_implants_hardware": "ഇംപ്ലാന്റുകൾ/ഹാർഡ്‌വെയർ ഉണ്ടോ?",
        "question_4_mri": "ചോദ്യം 4: എം.ആർ.ഐ റിപ്പോർട്ട്",
        "mri_scan_medical_report": "എം.ആർ.ഐ സ്കാൻ / മെഡിക്കൽ റിപ്പോർട്ട്",
        "mri_hint": "എം.ആർ.ഐ റിപ്പോർട്ട് ഉണ്ടെങ്കിൽ, ഗ്രേഡ് (KL Grade) തിരഞ്ഞെടുക്കുക.",
        "mri_normal_none": "സാധാരണം / ഇല്ല",
        "mri_normal_desc": "എം.ആർ.ഐ ഇല്ല അല്ലെങ്കിൽ ആരോഗ്യമുള്ള സന്ധികൾ",
        "mri_grade1_doubtful": "ഗ്രേഡ് 1: സംശയാസ്പദം",
        "mri_grade1_desc": "സന്ധിയിലെ വിടവ് ചുരുങ്ങാനുള്ള സാധ്യത",
        "mri_grade2_mild": "ഗ്രേഡ് 2: നേരിയത്",
        "mri_grade2_desc": "വ്യക്തമായ ഓസ്റ്റിയോഫൈറ്റുകൾ, ചുരുങ്ങാൻ സാധ്യത",
        "mri_grade3_moderate": "ഗ്രേഡ് 3: മിതമായത്",
        "mri_grade3_desc": "ഒന്നിലധികം ഓസ്റ്റിയോഫൈറ്റുകൾ, വ്യക്തമായ ചുരുങ്ങൽ",
        "mri_grade4_severe": "ഗ്രേഡ് 4: ഗുരുതരം",
        "mri_grade4_desc": "വലിയ ഓസ്റ്റിയോഫൈറ്റുകൾ, ഗുരുതരമായ ചുരുങ്ങൽ",
        "question_5_symptoms": "ചോദ്യം 5: ലക്ഷണങ്ങൾ",
        "expanded_symptoms": "വിശദമായ ലക്ഷണങ്ങൾ",
        "expanded_symptoms_hint": "മറ്റ് ലക്ഷണങ്ങൾ അനുഭവപ്പെടുന്നുണ്ടെങ്കിൽ തിരഞ്ഞെടുക്കുക.",
        "pain_characteristics": "വേദനയുടെ സ്വഭാവം",
        "pain_sharp": "കഠിനമായ വേദന",
        "pain_dull": "മങ്ങിയ വേദന",
        "pain_burning": "പുകച്ചിൽ",
        "pain_aching": "തുടർച്ചയായ വേദന",
        "pain_stabbing": "കുത്തിനോവുന്ന വേദന",
        "pain_throbbing": "മിടിക്കുന്ന വേദന",
        "stiffness_triggers": "മരവിപ്പിന് കാരണങ്ങൾ",
        "stiff_morning": "രാവിലെ",
        "stiff_after_sitting": "ഇരുന്ന ശേഷം",
        "stiff_after_inactivity": "നിഷ്ക്രിയത്വത്തിന് ശേഷം",
        "stiff_after_exercise": "വ്യായാമത്തിന് ശേഷം",
        "other_observations": "മറ്റ് ലക്ഷണങ്ങൾ",
        "sym_warmth": "ചൂട് തോന്നുക",
        "sym_redness": "ചുവപ്പ് നിറം",
        "sym_tenderness": "തൊടുമ്പോൾ വേദന",
        "sym_clicking": "ക്ലിക്ക് ശബ്ദം",
        "sym_grinding": "ഉരയുന്ന ശബ്ദം",
        "sym_locking": "സന്ധി ലോക്കാവുക",
        "sym_giving_way": "സന്ധി തെന്നിമാറുക",
        "sym_instability": "അസ്ഥിരത",
        "sym_reduced_mobility": "ചലനശേഷി കുറയുക"
    },
    "as": {
        "past_medical_history": "পূৰ্বৰ চিকিৎসাৰ ইতিহাস",
        "previous_diagnosis_of_arthritis": "আৰ্থ্ৰাইটিছৰ পূৰ্বৰ নিদান",
        "previous_joint_pain_episodes": "পূৰ্বৰ গাঁঠিৰ বিষৰ ঘটনা",
        "chronic_joint_problems": "দীৰ্ঘদিনীয়া গাঁঠিৰ সমস্যা",
        "previous_joint_inflammation_swelling": "গাঁঠিৰ ফুলা/প্ৰদাহ",
        "history_of_injury_to_this_joint": "এই গাঁঠিত আঘাতৰ ইতিহাস",
        "for_side_joint": "{side} {joint} ৰ বাবে",
        "past_surgeries": "পূৰ্বৰ অস্ত্ৰোপচাৰ",
        "have_you_had_surgery_on_this_joint": "আপোনাৰ এই গাঁঠিত অস্ত্ৰোপচাৰ হৈছে নেকি?",
        "surgery_details": "অস্ত্ৰোপচাৰৰ বিৱৰণ",
        "type_of_surgery": "অস্ত্ৰোপচাৰৰ প্ৰকাৰ",
        "are_there_implants_hardware": "কোনো ইমপ্লাণ্ট/হাৰ্ডৱেৰ আছেনে?",
        "question_4_mri": "প্ৰশ্ন ৪: এম আৰ আই ৰিপোৰ্ট",
        "mri_scan_medical_report": "এম আৰ আই স্কেন / মেডিকেল ৰিপোৰ্ট",
        "mri_hint": "ৰোগীৰ এম আৰ আই ৰিপোৰ্ট থাকিলে, গ্ৰেড (KL Grade) বাছক।",
        "mri_normal_none": "স্বাভাৱিক / নাই",
        "mri_normal_desc": "এম আৰ আই নাই বা সুস্থ গাঁঠি",
        "mri_grade1_doubtful": "গ্ৰেড ১: সন্দেহজনক",
        "mri_grade1_desc": "গাঁঠিৰ স্থান সন্দেহজনকভাৱে ঠেক হোৱা",
        "mri_grade2_mild": "গ্ৰেড ২: সামান্য",
        "mri_grade2_desc": "নিশ্চিত অষ্টিঅ'ফাইট, সম্ভাৱ্য ঠেক হোৱা",
        "mri_grade3_moderate": "গ্ৰেড ৩: মজলীয়া",
        "mri_grade3_desc": "একাধিক অষ্টিঅ'ফাইট, নিশ্চিতভাৱে ঠেক হোৱা",
        "mri_grade4_severe": "গ্ৰেড ৪: গুৰুতৰ",
        "mri_grade4_desc": "ডাঙৰ অষ্টিঅ'ফাইট, গুৰুতৰভাৱে ঠেক হোৱা",
        "question_5_symptoms": "প্ৰশ্ন ৫: লক্ষণসমূহ",
        "expanded_symptoms": "বিতং লক্ষণসমূহ",
        "expanded_symptoms_hint": "আপুনি অন্য কোনো লক্ষণ অনুভৱ কৰি থাকিলে বাছক।",
        "pain_characteristics": "বিষৰ প্ৰকাৰ",
        "pain_sharp": "তীব্ৰ বিষ",
        "pain_dull": "মৃদু বিষ",
        "pain_burning": "পোৰণি",
        "pain_aching": "নিৰন্তৰ বিষ",
        "pain_stabbing": "বিন্ধাৰ দৰে বিষ",
        "pain_throbbing": "ধপধপনি বিষ",
        "stiffness_triggers": "জড়তাৰ কাৰণসমূহ",
        "stiff_morning": "ৰাতিপুৱা",
        "stiff_after_sitting": "বহি থকাৰ পিছত",
        "stiff_after_inactivity": "নিষ্ক্ৰিয়তাৰ পিছত",
        "stiff_after_exercise": "ব্যায়ামৰ পিছত",
        "other_observations": "অন্যান্য লক্ষণ",
        "sym_warmth": "গৰম অনুভৱ",
        "sym_redness": "ৰঙা পৰা",
        "sym_tenderness": "স্পৰ্শ কৰিলে বিষোৱা",
        "sym_clicking": "ক্লিক শব্দ",
        "sym_grinding": "ঘঁহনি খোৱা শব্দ",
        "sym_locking": "গাঁঠি লাগি ধৰা",
        "sym_giving_way": "গাঁঠি পিছলি যোৱা",
        "sym_instability": "অস্থিৰতা",
        "sym_reduced_mobility": "গতিশীলতা হ্ৰাস পোৱা"
    }
}

def update_lang(lang_code, translations_dict):
    path = f"d:/OsteoSense/app/assets/translations/{lang_code}.json"
    with open(path, 'r', encoding='utf-8-sig') as f:
        data = json.load(f)
    
    updated = 0
    for k, v in translations_dict.items():
        data[k] = v
        updated += 1
        
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"Updated {updated} keys in {lang_code}.json")

for lang, trans_dict in translations.items():
    update_lang(lang, trans_dict)

print("All done!")
