name: iOS Build

on:
  push:
    branches:
      - main
  # Manual trigger button in GitHub Actions
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS Unsigned IPA
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        working-directory: ./app
        
      - name: Build iOS App (No Sign)
        # --no-codesign is used so it can build without an Apple Developer Account
        run: flutter build ios --release --no-codesign
        working-directory: ./app
        
      - name: Create Unsigned IPA
        run: |
          cd app/build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r ios-app-release.ipa Payload
          
      - name: Upload iOS IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-unsigned
          path: app/build/ios/iphoneos/ios-app-release.ipa
