name: iOS Simulator Build

on:
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab
  push:
    branches: [ main, master ]

jobs:
  build-ios:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        working-directory: ./app
        run: |
          mkdir -p build/ios/SourcePackages
          flutter pub get

      - name: Patch Podfile for Firebase
        working-directory: ./app
        run: |
          rm -f ios/Podfile
          flutter config --enable-swift-package-manager
          flutter build ios --config-only --simulator --no-codesign || true
          ruby -i -pe 'gsub(/use_frameworks!/, "use_frameworks! :linkage => :static\n  use_modular_headers!")' ios/Podfile
          ruby -i -pe 'gsub(/flutter_additional_ios_build_settings\(target\)/, "flutter_additional_ios_build_settings(target)\n      target.build_configurations.each do |config|\n        config.build_settings[\"ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES\"] = \"YES\"\n      end")' ios/Podfile
          cat ios/Podfile

      - name: Build unsigned iOS App for Real Devices
        working-directory: ./app
        run: flutter build ios --release --no-codesign

      - name: Package into IPA for Sideloading
        working-directory: ./app
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r app-sideload.ipa Payload

      - name: Upload iOS IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-unsigned-ipa
          path: app/build/ios/iphoneos/app-sideload.ipa
          retention-days: 7
